<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\Country;
use App\Models\Province;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SpainCitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $spain = Country::where('iso_code', 'ESP')->firstOrFail();

        // 2. Obtener todas las provincias de España indexadas por nombre
        $provinces = Province::where('country_id', $spain->id)
            ->get()
            ->keyBy('name');

        $citiesByProvince = [
            'A Coruña' => [
                ['name' => 'A Baña', 'postal_code' => null],
                ['name' => 'A Capela', 'postal_code' => null],
                ['name' => 'A Coruña', 'postal_code' => null],
                ['name' => 'A Laracha', 'postal_code' => null],
                ['name' => 'A Pobra do Caramiñal', 'postal_code' => null],
                ['name' => 'Abegondo', 'postal_code' => null],
                ['name' => 'Ames', 'postal_code' => null],
                ['name' => 'Aranga', 'postal_code' => null],
                ['name' => 'Ares', 'postal_code' => null],
                ['name' => 'Arteixo', 'postal_code' => null],
                ['name' => 'Arzúa', 'postal_code' => null],
                ['name' => 'As Pontes de García Rodríguez', 'postal_code' => null],
                ['name' => 'As Somozas', 'postal_code' => null],
                ['name' => 'Bergondo', 'postal_code' => null],
                ['name' => 'Betanzos', 'postal_code' => null],
                ['name' => 'Boimorto', 'postal_code' => null],
                ['name' => 'Boiro', 'postal_code' => null],
                ['name' => 'Boqueixón', 'postal_code' => null],
                ['name' => 'Brión', 'postal_code' => null],
                ['name' => 'Cabana de Bergantiños', 'postal_code' => null],
                ['name' => 'Cabanas', 'postal_code' => null],
                ['name' => 'Camariñas', 'postal_code' => null],
                ['name' => 'Cambre', 'postal_code' => null],
                ['name' => 'Ames', 'postal_code' => null],
                ['name' => 'Carballo', 'postal_code' => null],
                ['name' => 'Cariño', 'postal_code' => null],
                ['name' => 'Carnota', 'postal_code' => null],
                ['name' => 'Carral', 'postal_code' => null],
                ['name' => 'Cedeira', 'postal_code' => null],
                ['name' => 'Cee', 'postal_code' => null],
                ['name' => 'Cerceda', 'postal_code' => null],
                ['name' => 'Cerdido', 'postal_code' => null],
                ['name' => 'Coirós', 'postal_code' => null],
                ['name' => 'Corcubión', 'postal_code' => null],
                ['name' => 'Coristanco', 'postal_code' => null],
                ['name' => 'Culleredo', 'postal_code' => null],
                ['name' => 'Curtis', 'postal_code' => null],
                ['name' => 'Dodro', 'postal_code' => null],
                ['name' => 'Dumbría', 'postal_code' => null],
                ['name' => 'Fene', 'postal_code' => null],
                ['name' => 'Ferrol', 'postal_code' => null],
                ['name' => 'Fisterra', 'postal_code' => null],
                ['name' => 'Frades', 'postal_code' => null],
                ['name' => 'Irixoa', 'postal_code' => null],
                ['name' => 'Laxe', 'postal_code' => null],
                ['name' => 'Lousame', 'postal_code' => null],
                ['name' => 'Malpica de Bergantiños', 'postal_code' => null],
                ['name' => 'Mañón', 'postal_code' => null],
                ['name' => 'Mazaricos', 'postal_code' => null],
                ['name' => 'Melide', 'postal_code' => null],
                ['name' => 'Mesía', 'postal_code' => null],
                ['name' => 'Miño', 'postal_code' => null],
                ['name' => 'Moeche', 'postal_code' => null],
                ['name' => 'Monfero', 'postal_code' => null],
                ['name' => 'Mugardos', 'postal_code' => null],
                ['name' => 'Muros', 'postal_code' => null],
                ['name' => 'Muxía', 'postal_code' => null],
                ['name' => 'Narón', 'postal_code' => null],
                ['name' => 'Neda', 'postal_code' => null],
                ['name' => 'Negreira', 'postal_code' => null],
                ['name' => 'Noia', 'postal_code' => null],
                ['name' => 'Oleiros', 'postal_code' => null],
                ['name' => 'Ordes', 'postal_code' => null],
                ['name' => 'Oroso', 'postal_code' => null],
                ['name' => 'Ortigueira', 'postal_code' => null],
                ['name' => 'Outes', 'postal_code' => null],
                ['name' => 'Oza-Cesuras', 'postal_code' => null],
                ['name' => 'Paderne', 'postal_code' => null],
                ['name' => 'Padrón', 'postal_code' => null],
                ['name' => 'Pino, O', 'postal_code' => null],
                ['name' => 'Ponteceso', 'postal_code' => null],
                ['name' => 'Pontedeume', 'postal_code' => null],
                ['name' => 'Porto do Son', 'postal_code' => null],
                ['name' => 'Rianxo', 'postal_code' => null],
                ['name' => 'Ribeira', 'postal_code' => null],
                ['name' => 'Rois', 'postal_code' => null],
                ['name' => 'Sada', 'postal_code' => null],
                ['name' => 'San Sadurniño', 'postal_code' => null],
                ['name' => 'Santa Comba', 'postal_code' => null],
                ['name' => 'Santiago de Compostela', 'postal_code' => null],
                ['name' => 'Santiso', 'postal_code' => null],
                ['name' => 'Sobrado', 'postal_code' => null],
                ['name' => 'Teo', 'postal_code' => null],
                ['name' => 'Toques', 'postal_code' => null],
                ['name' => 'Tordoia', 'postal_code' => null],
                ['name' => 'Touro', 'postal_code' => null],
                ['name' => 'Trazo', 'postal_code' => null],
                ['name' => 'Val do Dubra', 'postal_code' => null],
                ['name' => 'Valdoviño', 'postal_code' => null],
                ['name' => 'Vedra', 'postal_code' => null],
                ['name' => 'Vilarmaior', 'postal_code' => null],
                ['name' => 'Vilasantar', 'postal_code' => null],
                ['name' => 'Vimianzo', 'postal_code' => null],
                ['name' => 'Zas', 'postal_code' => null],
            ],
            'Álava' => [
                ['name' => 'Alegría-Dulantzi', 'postal_code' => null],
                ['name' => 'Amurrio', 'postal_code' => null],
                ['name' => 'Añana', 'postal_code' => null],
                ['name' => 'Aramaio', 'postal_code' => null],
                ['name' => 'Armiñón', 'postal_code' => null],
                ['name' => 'Arraia-Maeztu', 'postal_code' => null],
                ['name' => 'Arratzua-Ubarrundia', 'postal_code' => null],
                ['name' => 'Artziniega', 'postal_code' => null],
                ['name' => 'Asparrena', 'postal_code' => null],
                ['name' => 'Ayala/Aiara', 'postal_code' => null],
                ['name' => 'Baños de Ebro/Mañueta', 'postal_code' => null],
                ['name' => 'Barrundia', 'postal_code' => null],
                ['name' => 'Berantevilla', 'postal_code' => null],
                ['name' => 'Bernedo', 'postal_code' => null],
                ['name' => 'Campezo/Kanpezu', 'postal_code' => null],
                ['name' => 'Elburgo/Burgelu', 'postal_code' => null],
                ['name' => 'Elciego', 'postal_code' => null],
                ['name' => 'Elvillar/Bilar', 'postal_code' => null],
                ['name' => 'Erriberagoitia/Ribera Alta', 'postal_code' => null],
                ['name' => 'Harana/Valle de Arana', 'postal_code' => null],
                ['name' => 'Iruña de Oca/Iruña Oka', 'postal_code' => null],
                ['name' => 'Iruraiz-Gauna', 'postal_code' => null],
                ['name' => 'Kripan', 'postal_code' => null],
                ['name' => 'Kuartango', 'postal_code' => null],
                ['name' => 'Labastida/Bastida', 'postal_code' => null],
                ['name' => 'Lagrán', 'postal_code' => null],
                ['name' => 'Laguardia', 'postal_code' => null],
                ['name' => 'Lanciego/Lantziego', 'postal_code' => null],
                ['name' => 'Lantarón', 'postal_code' => null],
                ['name' => 'Lapuebla de Labarca', 'postal_code' => null],
                ['name' => 'Legutio', 'postal_code' => null],
                ['name' => 'Leza', 'postal_code' => null],
                ['name' => 'Moreda de Álava/Moreda Araba', 'postal_code' => null],
                ['name' => 'Navaridas', 'postal_code' => null],
                ['name' => 'Okondo', 'postal_code' => null],
                ['name' => 'Oyón-Oion', 'postal_code' => null],
                ['name' => 'Peñacerrada-Urizaharra', 'postal_code' => null],
                ['name' => 'Ribera Baja/Erribera Beitia', 'postal_code' => null],
                ['name' => 'Samaniego', 'postal_code' => null],
                ['name' => 'San Millán/Donemiliaga', 'postal_code' => null],
                ['name' => 'Urkabustaiz', 'postal_code' => null],
                ['name' => 'Valdegovía/Gaubea', 'postal_code' => null],
                ['name' => 'Villabuena de Álava/Eskuernaga', 'postal_code' => null],
                ['name' => 'Vitoria-Gasteiz', 'postal_code' => null],
                ['name' => 'Yécora/Iekora', 'postal_code' => null],
                ['name' => 'Zalduondo', 'postal_code' => null],
                ['name' => 'Zambrana', 'postal_code' => null],
                ['name' => 'Zigoitia', 'postal_code' => null],
                ['name' => 'Zuia', 'postal_code' => null],
            ],
            'Albacete' => [
                ['name' => 'Abengibre', 'postal_code' => null],
                ['name' => 'Alatoz', 'postal_code' => null],
                ['name' => 'Albacete', 'postal_code' => null],
                ['name' => 'Albatana', 'postal_code' => null],
                ['name' => 'Alborea', 'postal_code' => null],
                ['name' => 'Alcadozo', 'postal_code' => null],
                ['name' => 'Alcalá del Júcar', 'postal_code' => null],
                ['name' => 'Alcaraz', 'postal_code' => null],
                ['name' => 'Almansa', 'postal_code' => null],
                ['name' => 'Alpera', 'postal_code' => null],
                ['name' => 'Ayna', 'postal_code' => null],
                ['name' => 'Balazote', 'postal_code' => null],
                ['name' => 'Balsa de Ves', 'postal_code' => null],
                ['name' => 'Barrax', 'postal_code' => null],
                ['name' => 'Bienservida', 'postal_code' => null],
                ['name' => 'Bogarra', 'postal_code' => null],
                ['name' => 'Bonete', 'postal_code' => null],
                ['name' => 'Carcelén', 'postal_code' => null],
                ['name' => 'Casas de Juan Núñez', 'postal_code' => null],
                ['name' => 'Casas de Lázaro', 'postal_code' => null],
                ['name' => 'Casas de Ves', 'postal_code' => null],
                ['name' => 'Casas-Ibáñez', 'postal_code' => null],
                ['name' => 'Caudete', 'postal_code' => null],
                ['name' => 'Cenizate', 'postal_code' => null],
                ['name' => 'Chinchilla de Monte-Aragón', 'postal_code' => null],
                ['name' => 'Corral-Rubio', 'postal_code' => null],
                ['name' => 'Cotillas', 'postal_code' => null],
                ['name' => 'El Ballestero', 'postal_code' => null],
                ['name' => 'El Bonillo', 'postal_code' => null],
                ['name' => 'Elche de la Sierra', 'postal_code' => null],
                ['name' => 'Férez', 'postal_code' => null],
                ['name' => 'Fuensanta', 'postal_code' => null],
                ['name' => 'Fuente-Álamo', 'postal_code' => null],
                ['name' => 'Fuentealbilla', 'postal_code' => null],
                ['name' => 'Golosalvo', 'postal_code' => null],
                ['name' => 'Hellín', 'postal_code' => null],
                ['name' => 'Higueruela', 'postal_code' => null],
                ['name' => 'Hoya-Gonzalo', 'postal_code' => null],
                ['name' => 'Jorquera', 'postal_code' => null],
                ['name' => 'La Gineta', 'postal_code' => null],
                ['name' => 'La Herrera', 'postal_code' => null],
                ['name' => 'La Recueja', 'postal_code' => null],
                ['name' => 'La Roda', 'postal_code' => null],
                ['name' => 'Letur', 'postal_code' => null],
                ['name' => 'Lezuza', 'postal_code' => null],
                ['name' => 'Liétor', 'postal_code' => null],
                ['name' => 'Madrigueras', 'postal_code' => null],
                ['name' => 'Mahora', 'postal_code' => null],
                ['name' => 'Masegoso', 'postal_code' => null],
                ['name' => 'Minaya', 'postal_code' => null],
                ['name' => 'Molinicos', 'postal_code' => null],
                ['name' => 'Montalvos', 'postal_code' => null],
                ['name' => 'Montealegre del Castillo', 'postal_code' => null],
                ['name' => 'Motilleja', 'postal_code' => null],
                ['name' => 'Munera', 'postal_code' => null],
                ['name' => 'Navas de Jorquera', 'postal_code' => null],
                ['name' => 'Nerpio', 'postal_code' => null],
                ['name' => 'Ontur', 'postal_code' => null],
                ['name' => 'Ossa de Montiel', 'postal_code' => null],
                ['name' => 'Paterna del Madera', 'postal_code' => null],
                ['name' => 'Peñas de San Pedro', 'postal_code' => null],
                ['name' => 'Peñascosa', 'postal_code' => null],
                ['name' => 'Pétrola', 'postal_code' => null],
                ['name' => 'Povedilla', 'postal_code' => null],
                ['name' => 'Pozo Cañada', 'postal_code' => null],
                ['name' => 'Pozohondo', 'postal_code' => null],
                ['name' => 'Pozo-Lorente', 'postal_code' => null],
                ['name' => 'Pozuelo', 'postal_code' => null],
                ['name' => 'Riópar', 'postal_code' => null],
                ['name' => 'Robledo', 'postal_code' => null],
                ['name' => 'Salobre', 'postal_code' => null],
                ['name' => 'San Pedro', 'postal_code' => null],
                ['name' => 'Socovos', 'postal_code' => null],
                ['name' => 'Tarazona de la Mancha', 'postal_code' => null],
                ['name' => 'Tobarra', 'postal_code' => null],
                ['name' => 'Valdeganga', 'postal_code' => null],
                ['name' => 'Vianos', 'postal_code' => null],
                ['name' => 'Villa de Ves', 'postal_code' => null],
                ['name' => 'Villalgordo del Júcar', 'postal_code' => null],
                ['name' => 'Villamalea', 'postal_code' => null],
                ['name' => 'Villapalacios', 'postal_code' => null],
                ['name' => 'Villarrobledo', 'postal_code' => null],
                ['name' => 'Villatoya', 'postal_code' => null],
                ['name' => 'Villavaliente', 'postal_code' => null],
                ['name' => 'Villaverde de Guadalimar', 'postal_code' => null],
                ['name' => 'Viveros', 'postal_code' => null],
                ['name' => 'Yeste', 'postal_code' => null],
            ],
            'Alicante' => [
                ['name' => 'Adsubia', 'postal_code' => null],
                ['name' => 'Agost', 'postal_code' => null],
                ['name' => 'Agres', 'postal_code' => null],
                ['name' => 'Aigües', 'postal_code' => null],
                ['name' => 'Albatera', 'postal_code' => null],
                ['name' => 'Alcalalí', 'postal_code' => null],
                ['name' => 'Alcocer de Planes', 'postal_code' => null],
                ['name' => 'Alcoleja', 'postal_code' => null],
                ['name' => 'Alcoy/Alcoi', 'postal_code' => null],
                ['name' => 'Alfafara', 'postal_code' => null],
                ['name' => 'Alfas del Pi, l\'', 'postal_code' => null],
                ['name' => 'Algorfa', 'postal_code' => null],
                ['name' => 'Algueña', 'postal_code' => null],
                ['name' => 'Alicante/Alacant', 'postal_code' => null],
                ['name' => 'Almoradí', 'postal_code' => null],
                ['name' => 'Almudaina', 'postal_code' => null],
                ['name' => 'Alquería d\'Asnar, l\'', 'postal_code' => null],
                ['name' => 'Altea', 'postal_code' => null],
                ['name' => 'Aspe', 'postal_code' => null],
                ['name' => 'Balones', 'postal_code' => null],
                ['name' => 'Banyeres de Mariola', 'postal_code' => null],
                ['name' => 'Benasau', 'postal_code' => null],
                ['name' => 'Beneixama', 'postal_code' => null],
                ['name' => 'Benejúzar', 'postal_code' => null],
                ['name' => 'Benferri', 'postal_code' => null],
                ['name' => 'Biar', 'postal_code' => null],
                ['name' => 'Bigastro', 'postal_code' => null],
                ['name' => 'Callosa de Segura', 'postal_code' => null],
                ['name' => 'Callosa d\'en Sarrià', 'postal_code' => null],
                ['name' => 'Calp', 'postal_code' => null],
                ['name' => 'Campello, el', 'postal_code' => null],
                ['name' => 'Castalla', 'postal_code' => null],
                ['name' => 'Crevillent', 'postal_code' => null],
                ['name' => 'Dénia', 'postal_code' => null],
                ['name' => 'Dolores', 'postal_code' => null],
                ['name' => 'Elche/Elx', 'postal_code' => null],
                ['name' => 'Elda', 'postal_code' => null],
                ['name' => 'Guardamar del Segura', 'postal_code' => null],
                ['name' => 'Ibi', 'postal_code' => null],
                ['name' => 'Jávea/Xàbia', 'postal_code' => null],
                ['name' => 'Jijona/Xixona', 'postal_code' => null],
                ['name' => 'Monóvar/Monòver', 'postal_code' => null],
                ['name' => 'Mutxamel', 'postal_code' => null],
                ['name' => 'Novelda', 'postal_code' => null],
                ['name' => 'Nucía, la', 'postal_code' => null],
                ['name' => 'Orihuela', 'postal_code' => null],
                ['name' => 'Pego', 'postal_code' => null],
                ['name' => 'Petrer', 'postal_code' => null],
                ['name' => 'Pilar de la Horadada', 'postal_code' => null],
                ['name' => 'Pinoso', 'postal_code' => null],
                ['name' => 'Redován', 'postal_code' => null],
                ['name' => 'Rojales', 'postal_code' => null],
                ['name' => 'San Fulgencio', 'postal_code' => null],
                ['name' => 'San Vicente del Raspeig/Sant Vicent del Raspeig', 'postal_code' => null],
                ['name' => 'Santa Pola', 'postal_code' => null],
                ['name' => 'Sax', 'postal_code' => null],
                ['name' => 'Teulada', 'postal_code' => null],
                ['name' => 'Torrevieja', 'postal_code' => null],
                ['name' => 'Villajoyosa/Vila Joiosa, la', 'postal_code' => null],
                ['name' => 'Villena', 'postal_code' => null],
            ],
            'Almería' => [
                ['name' => 'Abrucena', 'postal_code' => null],
                ['name' => 'Adra', 'postal_code' => null],
                ['name' => 'Albox', 'postal_code' => null],
                ['name' => 'Alcolea', 'postal_code' => null],
                ['name' => 'Alcóntar', 'postal_code' => null],
                ['name' => 'Alcudia de Monteagud', 'postal_code' => null],
                ['name' => 'Alhabia', 'postal_code' => null],
                ['name' => 'Alhama de Almería', 'postal_code' => null],
                ['name' => 'Alicún', 'postal_code' => null],
                ['name' => 'Almería', 'postal_code' => null],
                ['name' => 'Almócita', 'postal_code' => null],
                ['name' => 'Alsodux', 'postal_code' => null],
                ['name' => 'Antas', 'postal_code' => null],
                ['name' => 'Arboleas', 'postal_code' => null],
                ['name' => 'Armuna de Almanzora', 'postal_code' => null],
                ['name' => 'Bacares', 'postal_code' => null],
                ['name' => 'Balanegra', 'postal_code' => null],
                ['name' => 'Bayárcal', 'postal_code' => null],
                ['name' => 'Bayarque', 'postal_code' => null],
                ['name' => 'Bédar', 'postal_code' => null],
                ['name' => 'Beires', 'postal_code' => null],
                ['name' => 'Benahadux', 'postal_code' => null],
                ['name' => 'Benitagla', 'postal_code' => null],
                ['name' => 'Benizalón', 'postal_code' => null],
                ['name' => 'Bentarique', 'postal_code' => null],
                ['name' => 'Berja', 'postal_code' => null],
                ['name' => 'Canjáyar', 'postal_code' => null],
                ['name' => 'Cantoria', 'postal_code' => null],
                ['name' => 'Carboneras', 'postal_code' => null],
                ['name' => 'Castro de Filabres', 'postal_code' => null],
                ['name' => 'Chercos', 'postal_code' => null],
                ['name' => 'Chirivel', 'postal_code' => null],
                ['name' => 'Cuevas del Almanzora', 'postal_code' => null],
                ['name' => 'Dalías', 'postal_code' => null],
                ['name' => 'Ejido, El', 'postal_code' => null],
                ['name' => 'Enix', 'postal_code' => null],
                ['name' => 'Felix', 'postal_code' => null],
                ['name' => 'Fines', 'postal_code' => null],
                ['name' => 'Fiñana', 'postal_code' => null],
                ['name' => 'Fondón', 'postal_code' => null],
                ['name' => 'Gádor', 'postal_code' => null],
                ['name' => 'Gallardos, Los', 'postal_code' => null],
                ['name' => 'Garrucha', 'postal_code' => null],
                ['name' => 'Gérgal', 'postal_code' => null],
                ['name' => 'Huércal de Almería', 'postal_code' => null],
                ['name' => 'Huércal-Overa', 'postal_code' => null],
                ['name' => 'Illar', 'postal_code' => null],
                ['name' => 'Instinción', 'postal_code' => null],
                ['name' => 'Laroya', 'postal_code' => null],
                ['name' => 'Laujar de Andarax', 'postal_code' => null],
                ['name' => 'Líjar', 'postal_code' => null],
                ['name' => 'Lubrín', 'postal_code' => null],
                ['name' => 'Lucainena de las Torres', 'postal_code' => null],
                ['name' => 'Lúcar', 'postal_code' => null],
                ['name' => 'Macael', 'postal_code' => null],
                ['name' => 'María', 'postal_code' => null],
                ['name' => 'Mojácar', 'postal_code' => null],
                ['name' => 'Níjar', 'postal_code' => null],
                ['name' => 'Olula del Río', 'postal_code' => null],
                ['name' => 'Oria', 'postal_code' => null],
                ['name' => 'Padules', 'postal_code' => null],
                ['name' => 'Pulpí', 'postal_code' => null],
                ['name' => 'Purchena', 'postal_code' => null],
                ['name' => 'Roquetas de Mar', 'postal_code' => null],
                ['name' => 'Serón', 'postal_code' => null],
                ['name' => 'Sorbas', 'postal_code' => null],
                ['name' => 'Tabernas', 'postal_code' => null],
                ['name' => 'Tíjola', 'postal_code' => null],
                ['name' => 'Turre', 'postal_code' => null],
                ['name' => 'Vera', 'postal_code' => null],
                ['name' => 'Vícar', 'postal_code' => null],
                ['name' => 'Zurgena', 'postal_code' => null],
            ],
            'Asturias' => [
                ['name' => 'Allande', 'postal_code' => null],
                ['name' => 'Aller', 'postal_code' => null],
                ['name' => 'Amieva', 'postal_code' => null],
                ['name' => 'Avilés', 'postal_code' => null],
                ['name' => 'Belmonte de Miranda', 'postal_code' => null],
                ['name' => 'Bimenes', 'postal_code' => null],
                ['name' => 'Boal', 'postal_code' => null],
                ['name' => 'Cabrales', 'postal_code' => null],
                ['name' => 'Cabranes', 'postal_code' => null],
                ['name' => 'Candamo', 'postal_code' => null],
                ['name' => 'Cangas de Onís', 'postal_code' => null],
                ['name' => 'Cangas del Narcea', 'postal_code' => null],
                ['name' => 'Caravia', 'postal_code' => null],
                ['name' => 'Carreño', 'postal_code' => null],
                ['name' => 'Caso', 'postal_code' => null],
                ['name' => 'Castrillón', 'postal_code' => null],
                ['name' => 'Castropol', 'postal_code' => null],
                ['name' => 'Coaña', 'postal_code' => null],
                ['name' => 'Colunga', 'postal_code' => null],
                ['name' => 'Corvera de Asturias', 'postal_code' => null],
                ['name' => 'Cudillero', 'postal_code' => null],
                ['name' => 'Degaña', 'postal_code' => null],
                ['name' => 'El Franco', 'postal_code' => null],
                ['name' => 'Gijón', 'postal_code' => null],
                ['name' => 'Gozón', 'postal_code' => null],
                ['name' => 'Grado', 'postal_code' => null],
                ['name' => 'Grandas de Salime', 'postal_code' => null],
                ['name' => 'Ibias', 'postal_code' => null],
                ['name' => 'Illano', 'postal_code' => null],
                ['name' => 'Illas', 'postal_code' => null],
                ['name' => 'Langreo', 'postal_code' => null],
                ['name' => 'Laviana', 'postal_code' => null],
                ['name' => 'Lena', 'postal_code' => null],
                ['name' => 'Llanera', 'postal_code' => null],
                ['name' => 'Llanes', 'postal_code' => null],
                ['name' => 'Mieres', 'postal_code' => null],
                ['name' => 'Morcín', 'postal_code' => null],
                ['name' => 'Nava', 'postal_code' => null],
                ['name' => 'Navia', 'postal_code' => null],
                ['name' => 'Noreña', 'postal_code' => null],
                ['name' => 'Onís', 'postal_code' => null],
                ['name' => 'Oviedo', 'postal_code' => null],
                ['name' => 'Parres', 'postal_code' => null],
                ['name' => 'Peñamellera Alta', 'postal_code' => null],
                ['name' => 'Peñamellera Baja', 'postal_code' => null],
                ['name' => 'Pesoz', 'postal_code' => null],
                ['name' => 'Piloña', 'postal_code' => null],
                ['name' => 'Ponga', 'postal_code' => null],
                ['name' => 'Pravia', 'postal_code' => null],
                ['name' => 'Proaza', 'postal_code' => null],
                ['name' => 'Quirós', 'postal_code' => null],
                ['name' => 'Ribadedeva', 'postal_code' => null],
                ['name' => 'Ribadesella', 'postal_code' => null],
                ['name' => 'Ribera de Arriba', 'postal_code' => null],
                ['name' => 'Riosa', 'postal_code' => null],
                ['name' => 'Salas', 'postal_code' => null],
                ['name' => 'San Martín de Oscos', 'postal_code' => null],
                ['name' => 'San Martín del Rey Aurelio', 'postal_code' => null],
                ['name' => 'San Tirso de Abres', 'postal_code' => null],
                ['name' => 'Santa Eulalia de Oscos', 'postal_code' => null],
                ['name' => 'Santo Adriano', 'postal_code' => null],
                ['name' => 'Sariego', 'postal_code' => null],
                ['name' => 'Siero', 'postal_code' => null],
                ['name' => 'Sobrescobio', 'postal_code' => null],
                ['name' => 'Somiedo', 'postal_code' => null],
                ['name' => 'Soto del Barco', 'postal_code' => null],
                ['name' => 'Tapia de Casariego', 'postal_code' => null],
                ['name' => 'Taramundi', 'postal_code' => null],
                ['name' => 'Teverga', 'postal_code' => null],
                ['name' => 'Tineo', 'postal_code' => null],
                ['name' => 'Valdés', 'postal_code' => null],
                ['name' => 'Vegadeo', 'postal_code' => null],
                ['name' => 'Villanueva de Oscos', 'postal_code' => null],
                ['name' => 'Villaviciosa', 'postal_code' => null],
                ['name' => 'Villayón', 'postal_code' => null],
                ['name' => 'Yernes y Tameza', 'postal_code' => null],
            ],
            'Ávila' => [
                ['name' => 'Adanero', 'postal_code' => null],
                ['name' => 'Albornos', 'postal_code' => null],
                ['name' => 'Aldeanueva de Santa Cruz', 'postal_code' => null],
                ['name' => 'Amavida', 'postal_code' => null],
                ['name' => 'Arévalo', 'postal_code' => null],
                ['name' => 'Arenas de San Pedro', 'postal_code' => null],
                ['name' => 'Ávila', 'postal_code' => null],
                ['name' => 'Barco de Ávila, El', 'postal_code' => null],
                ['name' => 'Barraco, El', 'postal_code' => null],
                ['name' => 'Burgohondo', 'postal_code' => null],
                ['name' => 'Candeleda', 'postal_code' => null],
                ['name' => 'Casavieja', 'postal_code' => null],
                ['name' => 'Cebreros', 'postal_code' => null],
                ['name' => 'Hoyos del Espino', 'postal_code' => null],
                ['name' => 'Lanzahíta', 'postal_code' => null],
                ['name' => 'Madrigal de las Altas Torres', 'postal_code' => null],
                ['name' => 'Maello', 'postal_code' => null],
                ['name' => 'Navaluenga', 'postal_code' => null],
                ['name' => 'Piedrahíta', 'postal_code' => null],
                ['name' => 'Sotillo de la Adrada', 'postal_code' => null],
                ['name' => 'Tiemblo, El', 'postal_code' => null],
            ],
            'Badajoz' => [
                ['name' => 'Acedera', 'postal_code' => null],
                ['name' => 'Aceuchal', 'postal_code' => null],
                ['name' => 'Ahillones', 'postal_code' => null],
                ['name' => 'Alange', 'postal_code' => null],
                ['name' => 'Albuera, La', 'postal_code' => null],
                ['name' => 'Alburquerque', 'postal_code' => null],
                ['name' => 'Alconchel', 'postal_code' => null],
                ['name' => 'Alconera', 'postal_code' => null],
                ['name' => 'Aljucén', 'postal_code' => null],
                ['name' => 'Almendral', 'postal_code' => null],
                ['name' => 'Almendralejo', 'postal_code' => null],
                ['name' => 'Arroyo de San Serván', 'postal_code' => null],
                ['name' => 'Azuaga', 'postal_code' => null],
                ['name' => 'Badajoz', 'postal_code' => null],
                ['name' => 'Barcarrota', 'postal_code' => null],
                ['name' => 'Berlanga', 'postal_code' => null],
                ['name' => 'Cabeza del Buey', 'postal_code' => null],
                ['name' => 'Calamonte', 'postal_code' => null],
                ['name' => 'Campanario', 'postal_code' => null],
                ['name' => 'Castuera', 'postal_code' => null],
                ['name' => 'Don Benito', 'postal_code' => null],
                ['name' => 'Fregenal de la Sierra', 'postal_code' => null],
                ['name' => 'Fuente de Cantos', 'postal_code' => null],
                ['name' => 'Fuente del Maestre', 'postal_code' => null],
                ['name' => 'Guareña', 'postal_code' => null],
                ['name' => 'Herrera del Duque', 'postal_code' => null],
                ['name' => 'Higuera la Real', 'postal_code' => null],
                ['name' => 'Jerez de los Caballeros', 'postal_code' => null],
                ['name' => 'Llerena', 'postal_code' => null],
                ['name' => 'Mérida', 'postal_code' => null],
                ['name' => 'Montijo', 'postal_code' => null],
                ['name' => 'Olivenza', 'postal_code' => null],
                ['name' => 'Quintana de la Serena', 'postal_code' => null],
                ['name' => 'San Vicente de Alcántara', 'postal_code' => null],
                ['name' => 'Santa Marta', 'postal_code' => null],
                ['name' => 'Santos de Maimona, Los', 'postal_code' => null],
                ['name' => 'Talarrubia', 'postal_code' => null],
                ['name' => 'Villafranca de los Barros', 'postal_code' => null],
                ['name' => 'Villanueva de la Serena', 'postal_code' => null],
                ['name' => 'Zafra', 'postal_code' => null],
            ],
            'Baleares' => [
                ['name' => 'Alaior', 'postal_code' => null],
                ['name' => 'Alaró', 'postal_code' => null],
                ['name' => 'Alcúdia', 'postal_code' => null],
                ['name' => 'Algaida', 'postal_code' => null],
                ['name' => 'Andratx', 'postal_code' => null],
                ['name' => 'Ariany', 'postal_code' => null],
                ['name' => 'Artà', 'postal_code' => null],
                ['name' => 'Banyalbufar', 'postal_code' => null],
                ['name' => 'Binissalem', 'postal_code' => null],
                ['name' => 'Búger', 'postal_code' => null],
                ['name' => 'Bunyola', 'postal_code' => null],
                ['name' => 'Calvià', 'postal_code' => null],
                ['name' => 'Campanet', 'postal_code' => null],
                ['name' => 'Campos', 'postal_code' => null],
                ['name' => 'Capdepera', 'postal_code' => null],
                ['name' => 'Castell, Es', 'postal_code' => null],
                ['name' => 'Ciutadella de Menorca', 'postal_code' => null],
                ['name' => 'Consell', 'postal_code' => null],
                ['name' => 'Costitx', 'postal_code' => null],
                ['name' => 'Deià', 'postal_code' => null],
                ['name' => 'Eivissa', 'postal_code' => null],
                ['name' => 'Escorca', 'postal_code' => null],
                ['name' => 'Esporles', 'postal_code' => null],
                ['name' => 'Estellencs', 'postal_code' => null],
                ['name' => 'Felanitx', 'postal_code' => null],
                ['name' => 'Ferreries', 'postal_code' => null],
                ['name' => 'Formentera', 'postal_code' => null],
                ['name' => 'Fornalutx', 'postal_code' => null],
                ['name' => 'Inca', 'postal_code' => null],
                ['name' => 'Lloret de Vistalegre', 'postal_code' => null],
                ['name' => 'Lloseta', 'postal_code' => null],
                ['name' => 'Llubí', 'postal_code' => null],
                ['name' => 'Llucmajor', 'postal_code' => null],
                ['name' => 'Mahón', 'postal_code' => null],
                ['name' => 'Manacor', 'postal_code' => null],
                ['name' => 'Mancor de la Vall', 'postal_code' => null],
                ['name' => 'Maria de la Salut', 'postal_code' => null],
                ['name' => 'Marratxí', 'postal_code' => null],
                ['name' => 'Mercadal, Es', 'postal_code' => null],
                ['name' => 'Migjorn Gran, Es', 'postal_code' => null],
                ['name' => 'Montuïri', 'postal_code' => null],
                ['name' => 'Muro', 'postal_code' => null],
                ['name' => 'Palma de Mallorca', 'postal_code' => null],
                ['name' => 'Petra', 'postal_code' => null],
                ['name' => 'Pollença', 'postal_code' => null],
                ['name' => 'Porreres', 'postal_code' => null],
                ['name' => 'Sa Pobla', 'postal_code' => null],
                ['name' => 'Sant Antoni de Portmany', 'postal_code' => null],
                ['name' => 'Sant Joan', 'postal_code' => null],
                ['name' => 'Sant Joan de Labritja', 'postal_code' => null],
                ['name' => 'Sant Josep de sa Talaia', 'postal_code' => null],
                ['name' => 'Sant Llorenç des Cardassar', 'postal_code' => null],
                ['name' => 'Sant Lluís', 'postal_code' => null],
                ['name' => 'Santa Eugènia', 'postal_code' => null],
                ['name' => 'Santa Eulària des Riu', 'postal_code' => null],
                ['name' => 'Santa Margalida', 'postal_code' => null],
                ['name' => 'Santa María del Camí', 'postal_code' => null],
                ['name' => 'Santanyí', 'postal_code' => null],
                ['name' => 'Selva', 'postal_code' => null],
                ['name' => 'Sencelles', 'postal_code' => null],
                ['name' => 'Ses Salines', 'postal_code' => null],
                ['name' => 'Sineu', 'postal_code' => null],
                ['name' => 'Sóller', 'postal_code' => null],
                ['name' => 'Son Servera', 'postal_code' => null],
                ['name' => 'Valldemossa', 'postal_code' => null],
                ['name' => 'Vilafranca de Bonany', 'postal_code' => null],
            ],
            'Barcelona' => [
                ['name' => 'Abrera', 'postal_code' => null],
                ['name' => 'Aguilar de Segarra', 'postal_code' => null],
                ['name' => 'Aiguafreda', 'postal_code' => null],
                ['name' => 'Alella', 'postal_code' => null],
                ['name' => 'Alpens', 'postal_code' => null],
                ['name' => 'Ametlla del Vallès, l\'', 'postal_code' => null],
                ['name' => 'Arenys de Mar', 'postal_code' => null],
                ['name' => 'Arenys de Munt', 'postal_code' => null],
                ['name' => 'Argençola', 'postal_code' => null],
                ['name' => 'Argentona', 'postal_code' => null],
                ['name' => 'Artés', 'postal_code' => null],
                ['name' => 'Avià', 'postal_code' => null],
                ['name' => 'Avinyó', 'postal_code' => null],
                ['name' => 'Avinyonet del Penedès', 'postal_code' => null],
                ['name' => 'Badalona', 'postal_code' => null],
                ['name' => 'Badia del Vallès', 'postal_code' => null],
                ['name' => 'Bagà', 'postal_code' => null],
                ['name' => 'Balenyà', 'postal_code' => null],
                ['name' => 'Balsareny', 'postal_code' => null],
                ['name' => 'Barberà del Vallès', 'postal_code' => null],
                ['name' => 'Barcelona', 'postal_code' => null],
                ['name' => 'Begues', 'postal_code' => null],
                ['name' => 'Bellprat', 'postal_code' => null],
                ['name' => 'Berga', 'postal_code' => null],
                ['name' => 'Bigues i Riells', 'postal_code' => null],
                ['name' => 'Borredà', 'postal_code' => null],
                ['name' => 'Bruc, el', 'postal_code' => null],
                ['name' => 'Brull, el', 'postal_code' => null],
                ['name' => 'Cabanyes, les', 'postal_code' => null],
                ['name' => 'Cabrera d\'Anoia', 'postal_code' => null],
                ['name' => 'Cabrera de Mar', 'postal_code' => null],
                ['name' => 'Cabrils', 'postal_code' => null],
                ['name' => 'Calaf', 'postal_code' => null],
                ['name' => 'Calders', 'postal_code' => null],
                ['name' => 'Caldes de Montbui', 'postal_code' => null],
                ['name' => 'Caldes d\'Estrac', 'postal_code' => null],
                ['name' => 'Calella', 'postal_code' => null],
                ['name' => 'Calldetenes', 'postal_code' => null],
                ['name' => 'Callús', 'postal_code' => null],
                ['name' => 'Calonge de Segarra', 'postal_code' => null],
                ['name' => 'Campins', 'postal_code' => null],
                ['name' => 'Canet de Mar', 'postal_code' => null],
                ['name' => 'Canovelles', 'postal_code' => null],
                ['name' => 'Canyelles', 'postal_code' => null],
                ['name' => 'Capellades', 'postal_code' => null],
                ['name' => 'Capolat', 'postal_code' => null],
                ['name' => 'Cardedeu', 'postal_code' => null],
                ['name' => 'Cardona', 'postal_code' => null],
                ['name' => 'Carme', 'postal_code' => null],
                ['name' => 'Casserres', 'postal_code' => null],
                ['name' => 'Castell de l\'Areny', 'postal_code' => null],
                ['name' => 'Castellar de n\'Hug', 'postal_code' => null],
                ['name' => 'Castellar del Riu', 'postal_code' => null],
                ['name' => 'Castellar del Vallès', 'postal_code' => null],
                ['name' => 'Castellbell i el Vilar', 'postal_code' => null],
                ['name' => 'Castellbisbal', 'postal_code' => null],
                ['name' => 'Castelldefels', 'postal_code' => null],
                ['name' => 'Castellet i la Gornal', 'postal_code' => null],
                ['name' => 'Castellfollit del Boix', 'postal_code' => null],
                ['name' => 'Castellfollit de Riubregós', 'postal_code' => null],
                ['name' => 'Castellgalí', 'postal_code' => null],
                ['name' => 'Castellnou de Bages', 'postal_code' => null],
                ['name' => 'Castellolí', 'postal_code' => null],
                ['name' => 'Castellterçol', 'postal_code' => null],
                ['name' => 'Castellví de la Marca', 'postal_code' => null],
                ['name' => 'Castellví de Rosanes', 'postal_code' => null],
                ['name' => 'Centelles', 'postal_code' => null],
                ['name' => 'Cercs', 'postal_code' => null],
                ['name' => 'Cerdanyola del Vallès', 'postal_code' => null],
                ['name' => 'Cervelló', 'postal_code' => null],
                ['name' => 'Collbató', 'postal_code' => null],
                ['name' => 'Collsuspina', 'postal_code' => null],
                ['name' => 'Copons', 'postal_code' => null],
                ['name' => 'Corbera de Llobregat', 'postal_code' => null],
                ['name' => 'Cornellà de Llobregat', 'postal_code' => null],
                ['name' => 'Cubelles', 'postal_code' => null],
                ['name' => 'Dosrius', 'postal_code' => null],
                ['name' => 'Esparreguera', 'postal_code' => null],
                ['name' => 'Esplugues de Llobregat', 'postal_code' => null],
                ['name' => 'Figaró-Montmany', 'postal_code' => null],
                ['name' => 'Fígols', 'postal_code' => null],
                ['name' => 'Fogars de la Selva', 'postal_code' => null],
                ['name' => 'Fogars de Montclús', 'postal_code' => null],
                ['name' => 'Folgueroles', 'postal_code' => null],
                ['name' => 'Fonollosa', 'postal_code' => null],
                ['name' => 'Font-rubí', 'postal_code' => null],
                ['name' => 'Franqueses del Vallès, les', 'postal_code' => null],
                ['name' => 'Gaià', 'postal_code' => null],
                ['name' => 'Gallifa', 'postal_code' => null],
                ['name' => 'Garriga, la', 'postal_code' => null],
                ['name' => 'Gavà', 'postal_code' => null],
                ['name' => 'Gelida', 'postal_code' => null],
                ['name' => 'Gironella', 'postal_code' => null],
                ['name' => 'Gisclareny', 'postal_code' => null],
                ['name' => 'Granada, la', 'postal_code' => null],
                ['name' => 'Granera', 'postal_code' => null],
                ['name' => 'Granollers', 'postal_code' => null],
                ['name' => 'Gualba', 'postal_code' => null],
                ['name' => 'Guardiola de Berguedà', 'postal_code' => null],
                ['name' => 'Gurb', 'postal_code' => null],
                ['name' => 'Hospitalet de Llobregat, l\'', 'postal_code' => null],
                ['name' => 'Hostalets de Pierola, els', 'postal_code' => null],
                ['name' => 'Igualada', 'postal_code' => null],
                ['name' => 'Jorba', 'postal_code' => null],
                ['name' => 'Llacuna, la', 'postal_code' => null],
                ['name' => 'Llagosta, la', 'postal_code' => null],
                ['name' => 'Lliçà d\'Amunt', 'postal_code' => null],
                ['name' => 'Lliçà de Vall', 'postal_code' => null],
                ['name' => 'Llinars del Vallès', 'postal_code' => null],
                ['name' => 'Lluçà', 'postal_code' => null],
                ['name' => 'Malgrat de Mar', 'postal_code' => null],
                ['name' => 'Malla', 'postal_code' => null],
                ['name' => 'Manlleu', 'postal_code' => null],
                ['name' => 'Manresa', 'postal_code' => null],
                ['name' => 'Marganell', 'postal_code' => null],
                ['name' => 'Martorell', 'postal_code' => null],
                ['name' => 'Martorelles', 'postal_code' => null],
                ['name' => 'Masies de Roda, les', 'postal_code' => null],
                ['name' => 'Masies de Voltregà, les', 'postal_code' => null],
                ['name' => 'Masnou, el', 'postal_code' => null],
                ['name' => 'Masquefa', 'postal_code' => null],
                ['name' => 'Matadepera', 'postal_code' => null],
                ['name' => 'Mataró', 'postal_code' => null],
                ['name' => 'Mediona', 'postal_code' => null],
                ['name' => 'Moià', 'postal_code' => null],
                ['name' => 'Molins de Rei', 'postal_code' => null],
                ['name' => 'Mollet del Vallès', 'postal_code' => null],
                ['name' => 'Monistrol de Calders', 'postal_code' => null],
                ['name' => 'Monistrol de Montserrat', 'postal_code' => null],
                ['name' => 'Montcada i Reixac', 'postal_code' => null],
                ['name' => 'Montclar', 'postal_code' => null],
                ['name' => 'Montesquiu', 'postal_code' => null],
                ['name' => 'Montgat', 'postal_code' => null],
                ['name' => 'Montmajor', 'postal_code' => null],
                ['name' => 'Montmaneu', 'postal_code' => null],
                ['name' => 'Montmeló', 'postal_code' => null],
                ['name' => 'Montornès del Vallès', 'postal_code' => null],
                ['name' => 'Montseny', 'postal_code' => null],
                ['name' => 'Muntanyola', 'postal_code' => null],
                ['name' => 'Mura', 'postal_code' => null],
                ['name' => 'Navarcles', 'postal_code' => null],
                ['name' => 'Navàs', 'postal_code' => null],
                ['name' => 'Nou de Berguedà, la', 'postal_code' => null],
                ['name' => 'Òdena', 'postal_code' => null],
                ['name' => 'Olèrdola', 'postal_code' => null],
                ['name' => 'Olesa de Bonesvalls', 'postal_code' => null],
                ['name' => 'Olesa de Montserrat', 'postal_code' => null],
                ['name' => 'Olivella', 'postal_code' => null],
                ['name' => 'Olost', 'postal_code' => null],
                ['name' => 'Olvan', 'postal_code' => null],
                ['name' => 'Orís', 'postal_code' => null],
                ['name' => 'Oristà', 'postal_code' => null],
                ['name' => 'Orpí', 'postal_code' => null],
                ['name' => 'Òrrius', 'postal_code' => null],
                ['name' => 'Pacs del Penedès', 'postal_code' => null],
                ['name' => 'Palafolls', 'postal_code' => null],
                ['name' => 'Palau-solità i Plegamans', 'postal_code' => null],
                ['name' => 'Pallejà', 'postal_code' => null],
                ['name' => 'Palma de Cervelló, la', 'postal_code' => null],
                ['name' => 'Papiol, el', 'postal_code' => null],
                ['name' => 'Parets del Vallès', 'postal_code' => null],
                ['name' => 'Perafita', 'postal_code' => null],
                ['name' => 'Piera', 'postal_code' => null],
                ['name' => 'Pineda de Mar', 'postal_code' => null],
                ['name' => 'Pla del Penedès, el', 'postal_code' => null],
                ['name' => 'Pobla de Claramunt, la', 'postal_code' => null],
                ['name' => 'Pobla de Lillet, la', 'postal_code' => null],
                ['name' => 'Polinyà', 'postal_code' => null],
                ['name' => 'Pont de Vilomara i Rocafort, el', 'postal_code' => null],
                ['name' => 'Pontons', 'postal_code' => null],
                ['name' => 'Prat de Llobregat, el', 'postal_code' => null],
                ['name' => 'Prats de Lluçanès', 'postal_code' => null],
                ['name' => 'Prats de Rei, els', 'postal_code' => null],
                ['name' => 'Premià de Dalt', 'postal_code' => null],
                ['name' => 'Premià de Mar', 'postal_code' => null],
                ['name' => 'Puigdàlber', 'postal_code' => null],
                ['name' => 'Puig-reig', 'postal_code' => null],
                ['name' => 'Pujalt', 'postal_code' => null],
                ['name' => 'Quadrada de Segarra', 'postal_code' => null],
                ['name' => 'Quar, la', 'postal_code' => null],
                ['name' => 'Rajadell', 'postal_code' => null],
                ['name' => 'Rellinars', 'postal_code' => null],
                ['name' => 'Ripollet', 'postal_code' => null],
                ['name' => 'Roca del Vallès, la', 'postal_code' => null],
                ['name' => 'Roda de Ter', 'postal_code' => null],
                ['name' => 'Rubí', 'postal_code' => null],
                ['name' => 'Rubió', 'postal_code' => null],
                ['name' => 'Rupit i Pruit', 'postal_code' => null],
                ['name' => 'Sabadell', 'postal_code' => null],
                ['name' => 'Sagàs', 'postal_code' => null],
                ['name' => 'Saldes', 'postal_code' => null],
                ['name' => 'Sallent', 'postal_code' => null],
                ['name' => 'Sant Adrià de Besòs', 'postal_code' => null],
                ['name' => 'Sant Agustí de Lluçanès', 'postal_code' => null],
                ['name' => 'Sant Andreu de la Barca', 'postal_code' => null],
                ['name' => 'Sant Andreu de Llavaneres', 'postal_code' => null],
                ['name' => 'Sant Antoni de Vilamajor', 'postal_code' => null],
                ['name' => 'Sant Bartomeu del Grau', 'postal_code' => null],
                ['name' => 'Sant Boi de Llobregat', 'postal_code' => null],
                ['name' => 'Sant Boi de Lluçanès', 'postal_code' => null],
                ['name' => 'Sant Cebrià de Vallalta', 'postal_code' => null],
                ['name' => 'Sant Celoni', 'postal_code' => null],
                ['name' => 'Sant Climent de Llobregat', 'postal_code' => null],
                ['name' => 'Sant Cugat del Vallès', 'postal_code' => null],
                ['name' => 'Sant Cugat Sesgarrigues', 'postal_code' => null],
                ['name' => 'Sant Esteve de Palautordera', 'postal_code' => null],
                ['name' => 'Sant Esteve Sesrovires', 'postal_code' => null],
                ['name' => 'Sant Feliu de Codines', 'postal_code' => null],
                ['name' => 'Sant Feliu de Llobregat', 'postal_code' => null],
                ['name' => 'Sant Feliu Sasserra', 'postal_code' => null],
                ['name' => 'Sant Fost de Campsentelles', 'postal_code' => null],
                ['name' => 'Sant Fruitós de Bages', 'postal_code' => null],
                ['name' => 'Sant Hipòlit de Voltregà', 'postal_code' => null],
                ['name' => 'Sant Iscle de Vallalta', 'postal_code' => null],
                ['name' => 'Sant Jaume de Frontanyà', 'postal_code' => null],
                ['name' => 'Sant Joan de Vilatorrada', 'postal_code' => null],
                ['name' => 'Sant Joan Despí', 'postal_code' => null],
                ['name' => 'Sant Julià de Cerdanyola', 'postal_code' => null],
                ['name' => 'Sant Julià de Vilatorta', 'postal_code' => null],
                ['name' => 'Sant Just Desvern', 'postal_code' => null],
                ['name' => 'Sant Llorenç d\'Hortons', 'postal_code' => null],
                ['name' => 'Sant Llorenç Savall', 'postal_code' => null],
                ['name' => 'Sant Martí d\'Albars', 'postal_code' => null],
                ['name' => 'Sant Martí de Centelles', 'postal_code' => null],
                ['name' => 'Sant Martí de Tous', 'postal_code' => null],
                ['name' => 'Sant Martí Sarroca', 'postal_code' => null],
                ['name' => 'Sant Martí Sesgueioles', 'postal_code' => null],
                ['name' => 'Sant Mateu de Bages', 'postal_code' => null],
                ['name' => 'Sant Pere de Riudebitlles', 'postal_code' => null],
                ['name' => 'Sant Pere de Torelló', 'postal_code' => null],
                ['name' => 'Sant Pere de Vilamajor', 'postal_code' => null],
                ['name' => 'Sant Pere Sallavinera', 'postal_code' => null],
                ['name' => 'Sant Pol de Mar', 'postal_code' => null],
                ['name' => 'Sant Quintí de Mediona', 'postal_code' => null],
                ['name' => 'Sant Quirze de Besora', 'postal_code' => null],
                ['name' => 'Sant Quirze del Vallès', 'postal_code' => null],
                ['name' => 'Sant Quirze Safaja', 'postal_code' => null],
                ['name' => 'Sant Sadurní d\'Anoia', 'postal_code' => null],
                ['name' => 'Sant Sadurní d\'Osormort', 'postal_code' => null],
                ['name' => 'Sant Salvador de Guardiola', 'postal_code' => null],
                ['name' => 'Sant Vicenç de Castellet', 'postal_code' => null],
                ['name' => 'Sant Vicenç de Montalt', 'postal_code' => null],
                ['name' => 'Sant Vicenç de Torelló', 'postal_code' => null],
                ['name' => 'Sant Vicenç dels Horts', 'postal_code' => null],
                ['name' => 'Santa Coloma de Cervelló', 'postal_code' => null],
                ['name' => 'Santa Coloma de Gramenet', 'postal_code' => null],
                ['name' => 'Santa Eugènia de Berga', 'postal_code' => null],
                ['name' => 'Santa Eulàlia de Riuprimer', 'postal_code' => null],
                ['name' => 'Santa Eulàlia de Ronçana', 'postal_code' => null],
                ['name' => 'Santa Fe del Penedès', 'postal_code' => null],
                ['name' => 'Santa Margarida de Montbui', 'postal_code' => null],
                ['name' => 'Santa Margarida i els Monjos', 'postal_code' => null],
                ['name' => 'Santa Maria de Besora', 'postal_code' => null],
                ['name' => 'Santa Maria de Martorelles', 'postal_code' => null],
                ['name' => 'Santa Maria de Merlès', 'postal_code' => null],
                ['name' => 'Santa Maria de Miralles', 'postal_code' => null],
                ['name' => 'Santa Maria de Oló', 'postal_code' => null],
                ['name' => 'Santa Maria de Palautordera', 'postal_code' => null],
                ['name' => 'Santa Maria d\'Horta d\'Avinyó', 'postal_code' => null],
                ['name' => 'Santa Perpètua de Mogoda', 'postal_code' => null],
                ['name' => 'Santa Susanna', 'postal_code' => null],
                ['name' => 'Santpedor', 'postal_code' => null],
                ['name' => 'Sentmenat', 'postal_code' => null],
                ['name' => 'Seva', 'postal_code' => null],
                ['name' => 'Sitges', 'postal_code' => null],
                ['name' => 'Sobremunt', 'postal_code' => null],
                ['name' => 'Sora', 'postal_code' => null],
                ['name' => 'Subirats', 'postal_code' => null],
                ['name' => 'Súria', 'postal_code' => null],
                ['name' => 'Tagamanent', 'postal_code' => null],
                ['name' => 'Talamanca', 'postal_code' => null],
                ['name' => 'Taradell', 'postal_code' => null],
                ['name' => 'Tavèrnoles', 'postal_code' => null],
                ['name' => 'Tavertet', 'postal_code' => null],
                ['name' => 'Teià', 'postal_code' => null],
                ['name' => 'Terrassa', 'postal_code' => null],
                ['name' => 'Tiana', 'postal_code' => null],
                ['name' => 'Tona', 'postal_code' => null],
                ['name' => 'Tordera', 'postal_code' => null],
                ['name' => 'Torelló', 'postal_code' => null],
                ['name' => 'Torre de Claramunt, la', 'postal_code' => null],
                ['name' => 'Torrelavit', 'postal_code' => null],
                ['name' => 'Torrelles de Foix', 'postal_code' => null],
                ['name' => 'Torrelles de Llobregat', 'postal_code' => null],
                ['name' => 'Ullastrell', 'postal_code' => null],
                ['name' => 'Vacarisses', 'postal_code' => null],
                ['name' => 'Vallbona d\'Anoia', 'postal_code' => null],
                ['name' => 'Vallcebre', 'postal_code' => null],
                ['name' => 'Vallgorguina', 'postal_code' => null],
                ['name' => 'Vallirana', 'postal_code' => null],
                ['name' => 'Vallromanes', 'postal_code' => null],
                ['name' => 'Veciana', 'postal_code' => null],
                ['name' => 'Vic', 'postal_code' => null],
                ['name' => 'Vilada', 'postal_code' => null],
                ['name' => 'Viladecans', 'postal_code' => null],
                ['name' => 'Viladecavalls', 'postal_code' => null],
                ['name' => 'Vilafranca del Penedès', 'postal_code' => null],
                ['name' => 'Vilalba Sasserra', 'postal_code' => null],
                ['name' => 'Vilanova de Sau', 'postal_code' => null],
                ['name' => 'Vilanova del Camí', 'postal_code' => null],
                ['name' => 'Vilanova del Vallès', 'postal_code' => null],
                ['name' => 'Vilanova i la Geltrú', 'postal_code' => null],
                ['name' => 'Vilassar de Dalt', 'postal_code' => null],
                ['name' => 'Vilassar de Mar', 'postal_code' => null],
                ['name' => 'Vilobí del Penedès', 'postal_code' => null],
                ['name' => 'Viver i Serrateix', 'postal_code' => null],
            ],
            'Burgos' => [
                ['name' => 'Aranda de Duero', 'postal_code' => null],
                ['name' => 'Briviesca', 'postal_code' => null],
                ['name' => 'Burgos', 'postal_code' => null],
                ['name' => 'Lerma', 'postal_code' => null],
                ['name' => 'Miranda de Ebro', 'postal_code' => null],
                ['name' => 'Valle de Mena', 'postal_code' => null],
            ],
            'Cáceres' => [
                ['name' => 'Cáceres', 'postal_code' => null],
                ['name' => 'Coria', 'postal_code' => null],
                ['name' => 'Navalmoral de la Mata', 'postal_code' => null],
                ['name' => 'Plasencia', 'postal_code' => null],
                ['name' => 'Trujillo', 'postal_code' => null],
            ],
            'Cádiz' => [
                ['name' => 'Algeciras', 'postal_code' => null],
                ['name' => 'Arcos de la Frontera', 'postal_code' => null],
                ['name' => 'Barbate', 'postal_code' => null],
                ['name' => 'Cádiz', 'postal_code' => null],
                ['name' => 'Chiclana de la Frontera', 'postal_code' => null],
                ['name' => 'Chipiona', 'postal_code' => null],
                ['name' => 'Conil de la Frontera', 'postal_code' => null],
                ['name' => 'El Puerto de Santa María', 'postal_code' => null],
                ['name' => 'Jerez de la Frontera', 'postal_code' => null],
                ['name' => 'La Línea de la Concepción', 'postal_code' => null],
                ['name' => 'Puerto Real', 'postal_code' => null],
                ['name' => 'Rota', 'postal_code' => null],
                ['name' => 'San Fernando', 'postal_code' => null],
                ['name' => 'San Roque', 'postal_code' => null],
                ['name' => 'Sanlúcar de Barrameda', 'postal_code' => null],
                ['name' => 'Tarifa', 'postal_code' => null],
                ['name' => 'Ubrique', 'postal_code' => null],
            ],
            'Cantabria' => [
                ['name' => 'Camargo', 'postal_code' => null],
                ['name' => 'Castro-Urdiales', 'postal_code' => null],
                ['name' => 'Laredo', 'postal_code' => null],
                ['name' => 'Piélagos', 'postal_code' => null],
                ['name' => 'Santander', 'postal_code' => null],
                ['name' => 'Santoña', 'postal_code' => null],
                ['name' => 'Torrelavega', 'postal_code' => null],
            ],
            'Castellón' => [
                ['name' => 'Almassora', 'postal_code' => null],
                ['name' => 'Benicarló', 'postal_code' => null],
                ['name' => 'Benicàssim', 'postal_code' => null],
                ['name' => 'Burriana', 'postal_code' => null],
                ['name' => 'Castellón de la Plana', 'postal_code' => null],
                ['name' => 'Nules', 'postal_code' => null],
                ['name' => 'Onda', 'postal_code' => null],
                ['name' => 'Vall d\'Uixó, la', 'postal_code' => null],
                ['name' => 'Vila-real', 'postal_code' => null],
                ['name' => 'Vinaròs', 'postal_code' => null],
            ],
            'Ciudad Real' => [
                ['name' => 'Alcázar de San Juan', 'postal_code' => null],
                ['name' => 'Ciudad Real', 'postal_code' => null],
                ['name' => 'Daimiel', 'postal_code' => null],
                ['name' => 'Manzanares', 'postal_code' => null],
                ['name' => 'Miguelturra', 'postal_code' => null],
                ['name' => 'Puertollano', 'postal_code' => null],
                ['name' => 'Tomelloso', 'postal_code' => null],
                ['name' => 'Valdepeñas', 'postal_code' => null],
            ],
            'Córdoba' => [
                ['name' => 'Baena', 'postal_code' => null],
                ['name' => 'Cabra', 'postal_code' => null],
                ['name' => 'Córdoba', 'postal_code' => null],
                ['name' => 'Lucena', 'postal_code' => null],
                ['name' => 'Montilla', 'postal_code' => null],
                ['name' => 'Palma del Río', 'postal_code' => null],
                ['name' => 'Priego de Córdoba', 'postal_code' => null],
                ['name' => 'Puente Genil', 'postal_code' => null],
            ],
            'Cuenca' => [
                ['name' => 'Cuenca', 'postal_code' => null],
                ['name' => 'Tarancón', 'postal_code' => null],
            ],
            'Girona' => [
                ['name' => 'Banyoles', 'postal_code' => null],
                ['name' => 'Blanes', 'postal_code' => null],
                ['name' => 'Figueres', 'postal_code' => null],
                ['name' => 'Girona', 'postal_code' => null],
                ['name' => 'Lloret de Mar', 'postal_code' => null],
                ['name' => 'Olot', 'postal_code' => null],
                ['name' => 'Palafrugell', 'postal_code' => null],
                ['name' => 'Palamós', 'postal_code' => null],
                ['name' => 'Roses', 'postal_code' => null],
                ['name' => 'Salt', 'postal_code' => null],
                ['name' => 'Sant Feliu de Guíxols', 'postal_code' => null],
            ],
            'Granada' => [
                ['name' => 'Almuñécar', 'postal_code' => null],
                ['name' => 'Armilla', 'postal_code' => null],
                ['name' => 'Baza', 'postal_code' => null],
                ['name' => 'Granada', 'postal_code' => null],
                ['name' => 'Guadix', 'postal_code' => null],
                ['name' => 'Loja', 'postal_code' => null],
                ['name' => 'Maracena', 'postal_code' => null],
                ['name' => 'Motril', 'postal_code' => null],
            ],
            'Guadalajara' => [
                ['name' => 'Azuqueca de Henares', 'postal_code' => null],
                ['name' => 'Guadalajara', 'postal_code' => null],
            ],
            'Guipúzcoa' => [
                ['name' => 'Donostia/San Sebastián', 'postal_code' => null],
                ['name' => 'Eibar', 'postal_code' => null],
                ['name' => 'Errenteria', 'postal_code' => null],
                ['name' => 'Hernani', 'postal_code' => null],
                ['name' => 'Irun', 'postal_code' => null],
                ['name' => 'Pasaia', 'postal_code' => null],
                ['name' => 'Zarautz', 'postal_code' => null],
            ],
            'Huelva' => [
                ['name' => 'Almonte', 'postal_code' => null],
                ['name' => 'Ayamonte', 'postal_code' => null],
                ['name' => 'Huelva', 'postal_code' => null],
                ['name' => 'Isla Cristina', 'postal_code' => null],
                ['name' => 'Lepe', 'postal_code' => null],
                ['name' => 'Moguer', 'postal_code' => null],
            ],
            'Huesca' => [
                ['name' => 'Barbastro', 'postal_code' => null],
                ['name' => 'Huesca', 'postal_code' => null],
                ['name' => 'Monzón', 'postal_code' => null],
            ],
            'Jaén' => [
                ['name' => 'Alcalá la Real', 'postal_code' => null],
                ['name' => 'Andújar', 'postal_code' => null],
                ['name' => 'Jaén', 'postal_code' => null],
                ['name' => 'Linares', 'postal_code' => null],
                ['name' => 'Martos', 'postal_code' => null],
                ['name' => 'Úbeda', 'postal_code' => null],
            ],
            'La Rioja' => [
                ['name' => 'Calahorra', 'postal_code' => null],
                ['name' => 'Logroño', 'postal_code' => null],
            ],
            'Las Palmas' => [
                ['name' => 'Arrecife', 'postal_code' => null],
                ['name' => 'Arucas', 'postal_code' => null],
                ['name' => 'Ingenio', 'postal_code' => null],
                ['name' => 'Las Palmas de Gran Canaria', 'postal_code' => null],
                ['name' => 'Puerto del Rosario', 'postal_code' => null],
                ['name' => 'San Bartolomé de Tirajana', 'postal_code' => null],
                ['name' => 'Santa Lucía de Tirajana', 'postal_code' => null],
                ['name' => 'Telde', 'postal_code' => null],
            ],
            'León' => [
                ['name' => 'Le León', 'postal_code' => null],
                ['name' => 'Ponferrada', 'postal_code' => null],
                ['name' => 'San Andrés del Rabanedo', 'postal_code' => null],
            ],
            'Lleida' => [
                ['name' => 'Balaguer', 'postal_code' => null],
                ['name' => 'Lleida', 'postal_code' => null],
                ['name' => 'Tàrrega', 'postal_code' => null],
            ],
            'Lugo' => [
                ['name' => 'Lugo', 'postal_code' => null],
                ['name' => 'Monforte de Lemos', 'postal_code' => null],
                ['name' => 'Viveiro', 'postal_code' => null],
            ],
            'Madrid' => [
                ['name' => 'Alcalá de Henares', 'postal_code' => null],
                ['name' => 'Alcobendas', 'postal_code' => null],
                ['name' => 'Alcorcón', 'postal_code' => null],
                ['name' => 'Aranjuez', 'postal_code' => null],
                ['name' => 'Arganda del Rey', 'postal_code' => null],
                ['name' => 'Boadilla del Monte', 'postal_code' => null],
                ['name' => 'Colmenar Viejo', 'postal_code' => null],
                ['name' => 'Coslada', 'postal_code' => null],
                ['name' => 'Fuenlabrada', 'postal_code' => null],
                ['name' => 'Getafe', 'postal_code' => null],
                ['name' => 'Leganés', 'postal_code' => null],
                ['name' => 'Madrid', 'postal_code' => null],
                ['name' => 'Majadahonda', 'postal_code' => null],
                ['name' => 'Móstoles', 'postal_code' => null],
                ['name' => 'Parla', 'postal_code' => null],
                ['name' => 'Pinto', 'postal_code' => null],
                ['name' => 'Pozuelo de Alarcón', 'postal_code' => null],
                ['name' => 'Rivas-Vaciamadrid', 'postal_code' => null],
                ['name' => 'Las Rozas de Madrid', 'postal_code' => null],
                ['name' => 'San Sebastián de los Reyes', 'postal_code' => null],
                ['name' => 'Torrejón de Ardoz', 'postal_code' => null],
                ['name' => 'Valdemoro', 'postal_code' => null],
            ],
            'Málaga' => [
                ['name' => 'Alhaurín de la Torre', 'postal_code' => null],
                ['name' => 'Alhaurín el Grande', 'postal_code' => null],
                ['name' => 'Antequera', 'postal_code' => null],
                ['name' => 'Benalmádena', 'postal_code' => null],
                ['name' => 'Estepona', 'postal_code' => null],
                ['name' => 'Fuengirola', 'postal_code' => null],
                ['name' => 'Málaga', 'postal_code' => null],
                ['name' => 'Marbella', 'postal_code' => null],
                ['name' => 'Mijas', 'postal_code' => null],
                ['name' => 'Rincón de la Victoria', 'postal_code' => null],
                ['name' => 'Ronda', 'postal_code' => null],
                ['name' => 'Torremolinos', 'postal_code' => null],
                ['name' => 'Torrox', 'postal_code' => null],
                ['name' => 'Vélez-Málaga', 'postal_code' => null],
            ],
            'Murcia' => [
                ['name' => 'Alcantarilla', 'postal_code' => null],
                ['name' => 'Águilas', 'postal_code' => null],
                ['name' => 'Cartagena', 'postal_code' => null],
                ['name' => 'Cieza', 'postal_code' => null],
                ['name' => 'Lorca', 'postal_code' => null],
                ['name' => 'Mazarrón', 'postal_code' => null],
                ['name' => 'Molina de Segura', 'postal_code' => null],
                ['name' => 'Murcia', 'postal_code' => null],
                ['name' => 'San Javier', 'postal_code' => null],
                ['name' => 'Torre-Pacheco', 'postal_code' => null],
                ['name' => 'Yecla', 'postal_code' => null],
            ],
            'Navarra' => [
                ['name' => 'Pamplona/Iruña', 'postal_code' => null],
                ['name' => 'Tudela', 'postal_code' => null],
            ],
            'Ourense' => [
                ['name' => 'O Carballiño', 'postal_code' => null],
                ['name' => 'Ourense', 'postal_code' => null],
            ],
            'Palencia' => [
                ['name' => 'Palencia', 'postal_code' => null],
            ],
            'Pontevedra' => [
                ['name' => 'Lalín', 'postal_code' => null],
                ['name' => 'Marín', 'postal_code' => null],
                ['name' => 'Pontevedra', 'postal_code' => null],
                ['name' => 'Redondela', 'postal_code' => null],
                ['name' => 'Sanxenxo', 'postal_code' => null],
                ['name' => 'Vigo', 'postal_code' => null],
                ['name' => 'Vilagarcía de Arousa', 'postal_code' => null],
            ],
            'Salamanca' => [
                ['name' => 'Salamanca', 'postal_code' => null],
            ],
            'Santa Cruz de Tenerife' => [
                ['name' => 'Adeje', 'postal_code' => null],
                ['name' => 'Arona', 'postal_code' => null],
                ['name' => 'Granadilla de Abona', 'postal_code' => null],
                ['name' => 'La Orotava', 'postal_code' => null],
                ['name' => 'Los Realejos', 'postal_code' => null],
                ['name' => 'Puerto de la Cruz', 'postal_code' => null],
                ['name' => 'San Cristóbal de La Laguna', 'postal_code' => null],
                ['name' => 'Santa Cruz de Tenerife', 'postal_code' => null],
            ],
            'Segovia' => [
                ['name' => 'Segovia', 'postal_code' => null],
            ],
            'Sevilla' => [
                ['name' => 'Alcalá de Guadaíra', 'postal_code' => null],
                ['name' => 'Bormujos', 'postal_code' => null],
                ['name' => 'Camas', 'postal_code' => null],
                ['name' => 'Carmona', 'postal_code' => null],
                ['name' => 'Coria del Río', 'postal_code' => null],
                ['name' => 'Dos Hermanas', 'postal_code' => null],
                ['name' => 'Écija', 'postal_code' => null],
                ['name' => 'La Rinconada', 'postal_code' => null],
                ['name' => 'Lebrija', 'postal_code' => null],
                ['name' => 'Mairena del Aljarafe', 'postal_code' => null],
                ['name' => 'Morón de la Frontera', 'postal_code' => null],
                ['name' => 'Sevilla', 'postal_code' => null],
                ['name' => 'Utrera', 'postal_code' => null],
            ],
            'Soria' => [
                ['name' => 'Soria', 'postal_code' => null],
            ],
            'Tarragona' => [
                ['name' => 'Cambrils', 'postal_code' => null],
                ['name' => 'Reus', 'postal_code' => null],
                ['name' => 'Salou', 'postal_code' => null],
                ['name' => 'Tarragona', 'postal_code' => null],
                ['name' => 'Tortosa', 'postal_code' => null],
                ['name' => 'Valls', 'postal_code' => null],
                ['name' => 'Vila-seca', 'postal_code' => null],
            ],
            'Teruel' => [
                ['name' => 'Teruel', 'postal_code' => null],
            ],
            'Toledo' => [
                ['name' => 'Illescas', 'postal_code' => null],
                ['name' => 'Seseña', 'postal_code' => null],
                ['name' => 'Talavera de la Reina', 'postal_code' => null],
                ['name' => 'Toledo', 'postal_code' => null],
            ],
            'Valencia' => [
                ['name' => 'Alaquàs', 'postal_code' => null],
                ['name' => 'Alzira', 'postal_code' => null],
                ['name' => 'Burjassot', 'postal_code' => null],
                ['name' => 'Gandia', 'postal_code' => null],
                ['name' => 'Mislata', 'postal_code' => null],
                ['name' => 'Ontinyent', 'postal_code' => null],
                ['name' => 'Paterna', 'postal_code' => null],
                ['name' => 'Sagunto/Sagunt', 'postal_code' => null],
                ['name' => 'Torrent', 'postal_code' => null],
                ['name' => 'Valencia', 'postal_code' => null],
                ['name' => 'Xàtiva', 'postal_code' => null],
            ],
            'Valladolid' => [
                ['name' => 'Arroyo de la Encomienda', 'postal_code' => null],
                ['name' => 'Laguna de Duero', 'postal_code' => null],
                ['name' => 'Valladolid', 'postal_code' => null],
            ],
            'Vizcaya' => [
                ['name' => 'Barakaldo', 'postal_code' => null],
                ['name' => 'Basauri', 'postal_code' => null],
                ['name' => 'Bilbao', 'postal_code' => null],
                ['name' => 'Getxo', 'postal_code' => null],
                ['name' => 'Leioa', 'postal_code' => null],
                ['name' => 'Portugalete', 'postal_code' => null],
                ['name' => 'Santurtzi', 'postal_code' => null],
                ['name' => 'Sestao', 'postal_code' => null],
            ],
            'Zamora' => [
                ['name' => 'Zamora', 'postal_code' => null],
            ],
            'Zaragoza' => [
                ['name' => 'Calatayud', 'postal_code' => null],
                ['name' => 'Utebo', 'postal_code' => null],
                ['name' => 'Zaragoza', 'postal_code' => null],
            ],
        ];

        $provinceAliases = [
            'Baleares' => 'Illes Balears',
        ];

        foreach ($citiesByProvince as $provinceName => $cities) {
            $normalizedProvinceName = $provinceAliases[$provinceName] ?? $provinceName;

            // Seguridad: comprobar que la provincia existe
            if (! $provinces->has($normalizedProvinceName)) {
                $this->command?->warn("Provincia no encontrada: {$provinceName}");
                continue;
            }

            $province = $provinces->get($normalizedProvinceName);


            foreach ($cities as $cityData) {
                City::updateOrCreate(
                    [
                        'province_id' => $province->id,
                        'name'        => $cityData['name'],
                    ],
                    [
                        'postal_code' => $cityData['postal_code'] ?? null,
                    ]
                );
            }
        }
    }
}
